export interface Team{
    idTeam: number,
    idSoccerXML: number,
    intLoved: string;
    strTeam: string;
    strTeamShort: string;
    strAlternate: string;
    intFormedYear: number,
    strSport: string;
    strLeague: string;
    idLeague: number;
    strDivision: string;
    strManager: string;
    strStadium: string;
    strKeywords: string;
    strRSS: string;
    strStadiumThumb: string;
    strStadiumDescription: string;
    strStadiumLocation: string;
    intStadiumCapacity: number;
    strWebsite: string;
    strFacebook: string;
    strTwitter: string;
    strInstagram: string;
    strDescriptionEN: string;
    strDescriptionDE: string;
    strDescriptionFR: string;
    strDescriptionCN: string;
    strDescriptionIT: string;
    strDescriptionJP: string;
    strDescriptionRU: string;
    strDescriptionES: string;
    strDescriptionPT: string;
    strDescriptionSE: string;
    strDescriptionNL: string;
    strDescriptionHU: string;
    strDescriptionNO: string;
    strDescriptionIL: string;
    strDescriptionPL: string;
    strGender: string;
    strCountry: string;
    strTeamBadge: string;
    strTeamJersey: string;
    strTeamLogo: string;
    strTeamFanart1: string;
    strTeamFanart2: string;
    strTeamFanart3: string;
    strTeamFanart4: string;
    strTeamBanner: string;
    strYoutube: string;
    strLocked: string;
}